const $=s=>document.querySelector(s);let config,formats=[],timer;
let apiKey=localStorage.getItem('convertbox_api_key')||'';
function authHeaders(){return apiKey?{'X-API-Key':apiKey}:{}}
function showAuthPrompt(){$('#auth').hidden=false;$('#api-key').focus()}
async function apiFetch(url,opts={}){const res=await fetch(url,{...opts,headers:{...(opts.headers||{}),...authHeaders()}});if(res.status===401){showAuthPrompt();throw new Error('auth')}return res}
$('#auth-save').addEventListener('click',()=>{apiKey=$('#api-key').value.trim();localStorage.setItem('convertbox_api_key',apiKey);$('#auth').hidden=true;init()});
async function init(){try{config=await apiFetch('/api/v1/formats').then(r=>r.json());formats=config.formats;$('#file-help').textContent=`maks. ${Math.round(config.maxUploadBytes/1048576)} MB`;$('#ttl-copy').textContent=`Input dan output dibersihkan sekitar ${Math.round(config.jobTTLSeconds/60)} menit setelah selesai.`}catch(err){if(err.message!=='auth')$('#file-help').textContent='server sedang tidak tersedia'}}
function selectedFormat(file){const ext='.'+file.name.split('.').pop().toLowerCase();return formats.find(f=>f.extensions.includes(ext))}
function chooseFile(file){if(!file)return;const input=$('#file');if(file!==input.files[0]){const dt=new DataTransfer();dt.items.add(file);input.files=dt.files}const f=selectedFormat(file);$('#file-label').textContent=file.name;$('#file-help').textContent=`${(file.size/1048576).toFixed(2)} MB`;const out=$('#output');out.innerHTML='';if(!f){out.innerHTML='<option value="">Format tidak didukung</option>';out.disabled=true;$('#submit').disabled=true;return}f.outputs.forEach(id=>{const info=formats.find(x=>x.id===id),o=document.createElement('option');o.value=id;o.textContent=info.label;out.append(o)});out.disabled=false;$('#submit').disabled=file.size>config.maxUploadBytes}
$('#file').addEventListener('change',e=>chooseFile(e.target.files[0]));const drop=$('#drop');['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('over')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('over')}));drop.addEventListener('drop',e=>chooseFile(e.dataTransfer.files[0]));
$('#form').addEventListener('submit',async e=>{e.preventDefault();clearTimeout(timer);const button=$('#submit'),status=$('#status');button.disabled=true;status.hidden=false;status.className='status';status.textContent='Mengunggah dan memasukkan job ke antrean…';try{const res=await apiFetch('/api/v1/jobs',{method:'POST',body:new FormData(e.target)}),body=await res.json();if(!res.ok)throw new Error(body.error||'Upload gagal');poll(body.id)}catch(err){showError(err.message==='auth'?'API key diperlukan atau salah':err.message);button.disabled=false}});
async function poll(id){try{const res=await apiFetch(`/api/v1/jobs/${id}`),job=await res.json();if(!res.ok)throw new Error(job.error||'Job tidak ditemukan');if(job.status==='completed'){const expires=new Date(job.expiresAt).toLocaleTimeString();$('#status').innerHTML=`Selesai. File tersedia sampai sekitar ${expires}.<br><a href="#" id="dl-link">UNDUH ${escapeHTML(job.outputName)} ↓</a>`;$('#dl-link').addEventListener('click',ev=>{ev.preventDefault();downloadJob(id,job.outputName)});$('#submit').disabled=false;return}if(job.status==='failed')throw new Error(job.error||'Konversi gagal');$('#status').textContent=job.status==='queued'?'Menunggu giliran…':'Sedang mengonversi…';timer=setTimeout(()=>poll(id),1000)}catch(err){showError(err.message==='auth'?'API key diperlukan atau salah':err.message);$('#submit').disabled=false}}
async function downloadJob(id,name){try{const res=await apiFetch(`/api/v1/jobs/${id}/download`);if(!res.ok){const body=await res.json().catch(()=>({}));throw new Error(body.error||'Unduhan gagal')}const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(err){showError(err.message==='auth'?'API key diperlukan atau salah':err.message)}}
function showError(msg){const s=$('#status');s.hidden=false;s.className='status error';s.textContent=msg}function escapeHTML(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}init();
